Repository projectsyn/component-kyverno, pull requests merged in 2022-09, with the labels that each got.

#59 Add option to define ClusterPolicies via inventory
  .cruft.json
  .github/workflows/test.yaml
  Makefile
  Makefile.vars.mk
  class/defaults.yml
  class/kyverno.yml
  component/policies.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  renovate.json
  tests/golden/policies/kyverno/apps/kyverno.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_clusterpolicies.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_clusterreportchangerequests.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_generaterequests.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_policies.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_reportchangerequests.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/wgpolicyk8s.io_clusterpolicyreports.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/wgpolicyk8s.io_policyreports.yaml
  tests/golden/policies/kyverno/kyverno/01_namespace.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrole-kyverno-events.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrole-kyverno-generate.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrole-kyverno-policies.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrole-kyverno-userinfo.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrole-kyverno-view.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrole-kyverno-webhook.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrolebinding-kyverno-events.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrolebinding-kyverno-generate.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrolebinding-kyverno-policies.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrolebinding-kyverno-userinfo.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrolebinding-kyverno-view.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrolebinding-kyverno-webhook.yaml
  tests/golden/policies/kyverno/kyverno/02_configmap-kyverno-metrics.yaml
  tests/golden/policies/kyverno/kyverno/02_configmap-kyverno.yaml
  tests/golden/policies/kyverno/kyverno/02_deployment-kyverno.yaml
  tests/golden/policies/kyverno/kyverno/02_poddisruptionbudget-kyverno.yaml
  tests/golden/policies/kyverno/kyverno/02_role-kyverno-leaderelection.yaml
  tests/golden/policies/kyverno/kyverno/02_rolebinding-kyverno-leaderelection.yaml
  tests/golden/policies/kyverno/kyverno/02_service-kyverno-svc-metrics.yaml
  tests/golden/policies/kyverno/kyverno/02_service-kyverno-svc.yaml
  tests/golden/policies/kyverno/kyverno/02_serviceaccount-kyverno-service-account.yaml
  tests/golden/policies/kyverno/kyverno/03_additional-clusterroles.yaml
  tests/golden/policies/kyverno/kyverno/04_additional-rolebindings.yaml
  tests/golden/policies/kyverno/kyverno/10_monitoring/00_servicemonitor-kyverno.yaml
  tests/golden/policies/kyverno/kyverno/10_monitoring/10_prometheusrule_kyverno-alerts.yaml
  tests/golden/policies/kyverno/kyverno/10_secrets.yaml
  tests/golden/policies/kyverno/kyverno/80_policies.yaml
  tests/policies.yml
  tests/unit/validate_test.go
Labels: enhancement

#58 Gitignore jsonnetfile.json
  .gitignore
Labels: documentation

#47 Update dependency ghcr.io/kyverno/kyverno to v1.7.4
  class/defaults.yml
  tests/golden/defaults/kyverno/kyverno/00_crds/kyverno.io_clusterpolicies.yaml
  tests/golden/defaults/kyverno/kyverno/00_crds/kyverno.io_clusterreportchangerequests.yaml
  tests/golden/defaults/kyverno/kyverno/00_crds/kyverno.io_generaterequests.yaml
  tests/golden/defaults/kyverno/kyverno/00_crds/kyverno.io_policies.yaml
  tests/golden/defaults/kyverno/kyverno/00_crds/kyverno.io_reportchangerequests.yaml
  tests/golden/defaults/kyverno/kyverno/00_crds/wgpolicyk8s.io_clusterpolicyreports.yaml
  tests/golden/defaults/kyverno/kyverno/00_crds/wgpolicyk8s.io_policyreports.yaml
  tests/golden/defaults/kyverno/kyverno/02_clusterrole-kyverno-policies.yaml
  tests/golden/defaults/kyverno/kyverno/02_deployment-kyverno.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_clusterpolicies.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_clusterreportchangerequests.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_generaterequests.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_policies.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_reportchangerequests.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/wgpolicyk8s.io_clusterpolicyreports.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/wgpolicyk8s.io_policyreports.yaml
  tests/golden/policies/kyverno/kyverno/02_clusterrole-kyverno-policies.yaml
  tests/golden/policies/kyverno/kyverno/02_deployment-kyverno.yaml
Labels: dependency

#60 Add missing UpdateRequest CRD
  class/kyverno.yml
  tests/golden/defaults/kyverno/kyverno/00_crds/kyverno.io_updaterequests.yaml
  tests/golden/policies/kyverno/kyverno/00_crds/kyverno.io_updaterequests.yaml
Labels: bug
